name: Maven Build and Push Jar

on:
  workflow_dispatch:

jobs:
  build-and-push-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build JAR file
        run: mvn clean package

      - name: Publish JAR as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Run CI
          path: .github/workflows/hello.txt
      - name: Generate Documentation
        run: mvn site
